run-name: push ( ${{ github.actor }} )
name: Headless
on:
  push:
    branches:
      - '**'
jobs:
  my-test:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      failed: ${{steps.one.outputs.FAILED}}
      skipped: ${{steps.one.outputs.SKIPPED}}
    steps:
      - name: one
        id: one
        run: |
          {
            FAILED=""
            SKIPPED=""

            AAA='{"listSkippedSessions": ["One", "Two", "Three"]}'
            SKIPPED_JSON=$( jq -r '.listSkippedSessions' <<< $AAA )
            jq -c '.[]' <<< "$SKIPPED_JSON" | while read i; do
              echo "| $i |"
            done
          BBB='{"listFailedStepsPerLog": [
          {
            "sessionId": "gHN7sl578kGltZQF0bYvLQ",
            "failedSteps": 1
          },
          {
            "sessionId": "Hnghe9eeeEyI6QQoE682Kg",
            "failedSteps": 4
          }]
          }'
          SKIPPED="[ $(echo $(jq -r '.listSkippedSessions | to_entries | .[] | .value ' <<< $AAA )) ]"
          FAILED="[ $(echo $(jq -r '.listFailedStepsPerLog | to_entries | .[] | .value | .sessionId + " = "+(.failedSteps | @sh)' <<< $BBB )) ]"
          echo "$FAILED and $SKIPPED"
         
          } >> $GITHUB_STEP_SUMMARY
          {
            echo "FAILED=${FAILED}"
            echo "SKIPPED=${SKIPPED}"
          } >> $GITHUB_OUTPUT
  my-print:
    continue-on-error: true
    needs: my-test
    runs-on: ubuntu-latest
    outputs:
      failed: ${{steps.one.outputs.FAILED}}
      skipped: ${{steps.one.outputs.SKIPPED}}
    steps:
      - name: one
        run: |  
          echo "${{ needs.my-test.outputs.failed }}"
          echo "${{ needs.my-test.outputs.skipped }}"
          
